name: CPP CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install build-essential cmake
    - name: Build
      run: |
        for dir in CPP_*/; do
          for d in "$dir"*/; do
            echo "Building $d"
            make -C "$d"
            make -C "$d" fclean
          done
        done
  
