name: CPP Modules CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install compiler
        run: sudo apt-get install -y build-essential

      - name: detect modules changed
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
          | cut -d/ -f1 \
          | sort -u > modules.txt

      - name: build modules
        run: |
          while read module; do
            echo "Building $module"
            for dir in $(find $module -name Makefile); do
                make -C $(dirname $dir)
            done
          done < modules.txt